export const homeObjOne = {
  id: 'dashboard',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Vehicle Dashboard',
  headline: 'Check the condition of the vehicle at a glance',
  description: 'You can see the condition of my car at a glance at home, at work, at a cafe',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../../../../../asserts/1.svg').default,
  alt: 'Dashboard',
  dark: true,
  primary: true,
  darkText: false,
}
export const homeObjTwo = {
  id: 'analysis',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Analysis',
  headline: 'We will analyze your driving pattern.',
  description: 'Save fuel efficiency and enjoy a happy driving culture by correcting driving patterns!',
  buttonLabel: 'Learn More',
  imgStart: true,
  img: require('../../../../../../asserts/2.svg').default,
  alt: 'Pattern Analysis',
  dark: false,
  primary: false,
  darkText: true,
}
export const homeObjThree = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Sign Up Now',
  headline: 'You can enjoy our service',
  description: 'We promise the best service and will always fix any inconveniences.',
  buttonLabel: 'Start Now',
  imgStart: false,
  img: require('../../../../../../asserts/3.svg').default,
  alt: 'Dashboard',
  dark: false,
  primary: false,
  darkText: true,
}